DROP TABLE IF EXISTS ACCOUNT;

CREATE TABLE ACCOUNT (ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR, AGE INT);

INSERT INTO ACCOUNT (NAME, AGE) VALUES ('leekyunghee', 35);
INSERT INTO ACCOUNT (NAME, AGE) VALUES ('kimjinho', 37);
INSERT INTO ACCOUNT (NAME, AGE) VALUES ('kimsumi', 38);
INSERT INTO ACCOUNT (NAME, AGE) VALUES ('parkunmi', 33);